#########
# Reuse #
#########
variables:

##########
# Stages #
##########

stages:
  - Quality     # Quality checks, unit tests, lints, etc

###########
# Quality #
###########
.quality:
  stage: Quality
  image: node:10
  before_script:
    - npm install

Unit test:
  extends: .quality
  script:
    - npm run test
    - npm run coverage

Lint:
  extends: .quality
  script:
    - npm run lint

Audit:
  extends: .quality
  script:
    - npm run audit

Dependencies:
  extends: .quality
  allow_failure: true
  script:
    - npm outdated
