cache_key: &cache_key deps-{{ checksum "package.json" }}
job_defaults: &job_defaults
  docker:
  - image: circleci/node:10.5.0
  working_directory: ~/repo

version: 2
jobs:
  prepare:
    <<: *job_defaults
    steps:
    - checkout
    - restore_cache:
        key: *cache_key
    - run:
        name: install dependencies
        command: npm install
    - save_cache:
        key: *cache_key
        paths:
          - ./node_modules
  test:
    <<: *job_defaults
    steps:
    - checkout
    - restore_cache:
        key: *cache_key
    - run:
        name: run tests
        command: npm run test
  lint:
    <<: *job_defaults
    steps:
    - checkout
    - restore_cache:
        key: *cache_key
    - run:
        name: run linter
        command: npm run lint
  audit:
    <<: *job_defaults
    steps:
    - checkout
    - restore_cache:
        key: *cache_key
    - run:
        name: security audit
        command: npm run audit

workflows:
  version: 2
  test_and_lint:
    jobs:
      - prepare
      - test:
          requires:
          - prepare
      - lint:
          requires:
          - prepare
      - audit:
          requires:
          - prepare
